# Generated by Django 4.2 on 2023-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='person_list', to='core.course'),
        ),
    ]
