# Generated by Django 4.2 on 2023-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
