# Generated by Django 4.2 on 2023-04-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_dep_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.dep')),
            ],
        ),
    ]
