# Generated by Django 4.2 on 2023-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_employee_email_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
